export const en = {
	"MostPopularBooks": "Most popular books",
	'ActionBooks': 'Action books',
	'MayBeYouLike': 'Maybe you like',
	'TypeSomething': 'Type something...',
	'FavoritesUsers': 'Favorites users',
	'StartedBooks': 'Started books',
	'FavoriteBooks': 'Favorite books',
	'FinishedBooks': 'Finished books',
	'Books': 'Books',
	'Reviews': 'Reviews',
	'Favorite': 'Favorite',
	'UserBooks': 'Books',
	'UserReviews': 'Reviews',
	'NoDiscussions': 'No discussions',
	'Favorites': 'Favorites',
	'EnterPassword': 'Enter password',
	'addBook': 'Add book',
	'Settings': 'Settings',
	'ProfileSettings': 'Profile settings',
	'PasswordSettings': 'Password settings',
	'LanguageSettings': 'Language settings',
	'ReportAProblem': 'Report a problem',
	'SendFeedback': 'Send feedback',
	'Logout': 'Logout',
	'Update': 'Update',
	'EnterName': 'Enter name',
	'EnterEmail': 'Enter email',
	'ConfirmPassword': 'Confirm password',
	'EnterOldPassword': 'Enter old password',
	'EnterNewPassword': 'Enter new password',
	'ChangePassword': 'Change password',
	'ChoseLanguage': 'Chose language',
	'StayMessage': 'Stay Message',
	'SendReview': 'Send review',
	'Years': 'Years',
	'Pages': 'Pages',
	'Description': 'Description',
	'Register': 'Register',
	'Login': 'Login',
	'YouDontHaveAfavoriteBook': 'You dont have a favorite book',
	'YouDontHaveAStartedBook': 'You dont have a started book',
	'YouDontHaveAFinishedBook': 'You dont have a finished book',
	'CharacterProgress': 'Character progress:',
	'of': 'of',
	'pages': 'pages',
	'Characters': 'Characters',
	'You text must be a minimum 20 letter!': 'You text must be a minimum 20 letter!',
	'Send Review': 'Send Review',
	"Terrable": "Terrable",
	"Bad": "Bad",
	"Normal": "Normal",
	"Good": "Good",
	"Excellent": "Excellent",
	'Go Read': 'Go Read',
	'Delete book': 'Delete book',
	'add': 'Add',
	'None review!': 'None review!',
	'Send': 'Send',
	'Are you sure you want to logout from your account?'	: 'Are you sure you want to logout from your account?',
	'LOGOUT': 'LOGOUT',
	
}
