export const en = {
	MostPopularBooks: 'Most popular books',
	ActionBooks: 'Action books',
	MayBeYouLike: 'Maybe you like',
	TypeSomething: 'Type something...',
	FavoritesUsers: 'Favorites users',
	StartedBooks: 'Started books',
	FavoriteBooks: 'Favorite books',
	FinishedBooks: 'Finished books',
	Books: 'Books',
	Reviews: 'Reviews',
	Favorite: 'Favorite',
	'Finish book': 'Finish book',
	'hi': 'Hi',
	UserBooks: 'Books',
	UserReviews: 'Reviews',
	NoDiscussions: 'No discussions',
	Favorites: 'Favorites',
	EnterPassword: 'Enter password',
	addBook: 'Add book',
	Settings: 'Settings',
	ProfileSettings: 'Profile settings',
	PasswordSettings: 'Password settings',
	LanguageSettings: 'Language settings',
	ReportAProblem: 'Report a problem',
	SendFeedback: 'Send feedback',
	Logout: 'Logout',
	Update: 'Update',
	EnterName: 'Enter name',
	EnterEmail: 'Enter email',
	ConfirmPassword: 'Confirm password',
	EnterOldPassword: 'Enter old password',
	EnterNewPassword: 'Enter new password',
	ChangePassword: 'Change password',
	ChoseLanguage: 'Chose language',
	StayMessage: 'Stay Message',
	SendReview: 'Send review',
	Years: 'Years',
	Pages: 'Pages',
	Description: 'Description',
	Register: 'Register',
	Login: 'Login',
	YouDontHaveAfavoriteBook: 'You dont have a favorite book',
	YouDontHaveAStartedBook: 'You dont have a started book',
	YouDontHaveAFinishedBook: 'You dont have a finished book',
	CharacterProgress: 'Character progress:',
	of: 'of',
	pages: 'pages',
	Characters: 'Characters',
	'You text must be a minimum 20 letter!':
		'You text must be a minimum 20 letter!',
	'Send Review': 'Send Review',
	Terrable: 'Terrable',
	Bad: 'Bad',
	Normal: 'Normal',
	Good: 'Good',
	Excellent: 'Excellent',
	'Go Read': 'Go Read',
	'Delete book': 'Delete book',
	add: 'Add',
	'None review!': 'None review!',
	Send: 'Send',
	'Are you sure you want to logout from your account?':
		'Are you sure you want to logout from your account?',
	LOGOUT: 'LOGOUT',
	'Book already exists': 'Book already exists',
	'Please try again': 'Please try again',
	'Something went wrong': 'Something went wrong',
	'Something went wrong!': 'Something went wrong!',
	Error: 'Error',
	'None title': 'None title',
	'None author': 'None author',
	'None languages': 'None languages',
	'None genres': 'None genres',
	'Selected item please': 'Selected item please',
	'Add book': 'Add book',
	'Select epub': 'Select epub',
	UserRemoveFromFavorite: 'User remove from favorite',
	'You add user to favorites': 'You add user to favorites',
	'Success update profile': 'Success update profile',
	'Success update password': 'Success update password',
	'Book not loaded!': 'Book not loaded!',
	'You delete book!': 'You delete book!',
	'Error in message!': 'Error in message!',
	'You add book review!': 'You add book review!',
	'You add book to favorites!': 'You add book to favorites!',
	'You finish book!': 'You finish book!',
	'You add book!': 'You add book!',
	'You book remove from favorites!': 'You book remove from favorites!',
	Success: 'Success',
	'You message delete': 'You message delete',
	'You message copy': 'You message copy',
	Copy: 'Copy',
	Delete: 'Delete',
	'Min term length = 5': 'Min term length = 5',
	'RTK error': 'RTK error',
	'No Books': 'No Books',
	'You not have books': 'Not have books',
	'Random Books': 'Random Books',
	'Library': 'Library',
	'Continue Reading': 'Continue Reading',
	'Continue': 'Continue',
	'Favorite Authors': 'Favorite Authors',
	'Name must be less than 20 characters': 'Name must be less than 20 characters',
	'MaybeProblemWithGoogleApi': 'Maybe problem with google api',
	'They good day for read new book!': 'They good day for read new book!',
	'No internet connection for new content!': 'No internet connection for new content!',
	'dontHaveInternetAndSavedData': 'It looks like you dont have internet and saved data'
}
