export const ru = {
	MostPopularBooks: 'Самые популярные книги',
	ActionBooks: 'Книги в жанре боевик',
	MayBeYouLike: 'Возможно вам понравится',
	TypeSomething: 'Введите что-нибудь...',
	FavoritesUsers: 'Избранные пользователи',
	StartedBooks: 'Начатые книги',
	FavoriteBooks: 'Избранные книги',
	FinishedBooks: 'Прочитанные книги',
	Books: 'Книги',
	UserBooks: 'Книг',
	UserReviews: 'Отзывов',
	NoDiscussions: 'Нет обсуждений',
	Reviews: 'Отзывы',
	Favorite: 'Избранное',
	Favorites: 'Избранных',
	addBook: 'Добавить книгу',
	Settings: 'Настройки',
	ProfileSettings: 'Настройки профиля',
	PasswordSettings: 'Настройки пароля',
	LanguageSettings: 'Настройки языка',
	ReportAProblem: 'Сообщить о проблеме',
	SendFeedback: 'Отправить отзыв',
	Logout: 'Выйти',
	Update: 'Обновить',
	EnterName: 'Введите имя',
	EnterEmail: 'Введите почту',
	EnterPassword: 'Введите пароль',
	ConfirmPassword: 'Подтвердите пароль',
	EnterOldPassword: 'Введите старый пароль',
	EnterNewPassword: 'Введите новый пароль',
	ChangePassword: 'Изменить пароль',
	ChoseLanguage: 'Выберите язык',
	StayMessage: 'Оставьте сообщение',
	SendReview: 'Отправить отзыв',
	Years: 'Лет',
	Pages: 'Страниц',
	Description: 'Описание',
	Register: 'Регистрация',
	Login: 'Войти',
	YouDontHaveAfavoriteBook: 'У вас нет избранных книг',
	YouDontHaveAStartedBook: 'У вас нет начатых книг',
	YouDontHaveAFinishedBook: 'У вас нет прочитанных книг',
	CharacterProgress: 'Прогресс главы:',
	of: 'из',
	pages: 'страниц',
	Characters: 'Главы',
	'You text must be a minimum 20 letter!':
		'Ваш текст должен быть минимум 20 символов!',
	'Send Review': 'Отправить отзыв',
	Terrable: 'Ужасно',
	Bad: 'Плохо',
	Normal: 'Нормально',
	Good: 'Хорошо',
	Excellent: 'Отлично',
	'Go Read': 'Читать',
	'Delete book': 'Удалить книгу',
	add: 'Добавить',
	'None review!': 'Нет отзывов!',
	Send: 'Отправить',
	'Are you sure you want to logout from your account?':
		'Вы уверены, что хотите выйти из аккаунта?',
	LOGOUT: 'ВЫЙТИ',
	'Book already exists': 'Книга уже существует',
	'Please try again': 'Попробуйте еще раз',
	'Something went wrong': 'Что-то пошло не так',
	'Something went wrong!': 'Что-то пошло не так!',
	Error: 'Ошибка',
	'None title': 'Без названия',
	'None author': 'Без автора',
	'None languages': 'Без языка',
	'None genres': 'Без жанра',
	'Selected item please': 'Выберите элемент',
	'Add book': 'Добавить книгу',
	'Select epub': 'Выберите epub',
	UserRemoveFromFavorite: 'Пользователь удалил книгу из избранного',
	'You add user to favorites': 'Вы добавили пользователя в избранное',
	'Success update profile': 'Профиль успешно обновлен',
	'Success update password': 'Пароль успешно обновлен',
	'Book not loaded!': 'Книга не загружена!',
	'You delete book!': 'Вы удалили книгу!',
	'Error in message!': 'Ошибка в сообщении!',
	'You add book review!': 'Вы добавили отзыв к книге!',
	'You add book to favorites!': 'Вы добавили книгу в избранное!',
	'You finish book!': 'Вы прочитали книгу!',
	'You add book!': 'Вы добавили книгу!',
	'You book remove from favorites!': 'Вы удалили книгу из избранного!',
	Success: 'Успешно',
	'You message delete': 'Вы удалили сообщение',
	'You message copy': 'Вы скопировали сообщение',
	Copy: 'Копировать',
	Delete: 'Удалить',
	'Min term length = 5': 'Минимальная длина запроса = 5',
	'RTK error': 'Ошибка RTK',
	'No Books': 'Нет книг'
}
