export const ru = {
	"MostPopularBooks": "Самые популярные книги",
	'ActionBooks': 'Книги в жанре боевик',
	'MayBeYouLike': 'Возможно вам понравится',
	'TypeSomething': 'Введите что-нибудь...',
	'FavoritesUsers': 'Избранные пользователи',
	'StartedBooks': 'Начатые книги',
	'FavoriteBooks': 'Избранные книги',
	'FinishedBooks': 'Прочитанные книги',
	'Books': 'Книги',
	'UserBooks': 'Книг',
	'UserReviews': 'Отзывов',
	'NoDiscussions': 'Нет обсуждений',
	'Reviews': 'Отзывы',
	'Favorite': 'Избранное',
	'Favorites': 'Избранных',
	'addBook': 'Добавить книгу',
	'Settings': 'Настройки',
	'ProfileSettings': 'Настройки профиля',
	'PasswordSettings': 'Настройки пароля',
	'LanguageSettings': 'Настройки языка',
	'ReportAProblem': 'Сообщить о проблеме',
	'SendFeedback': 'Отправить отзыв',
	'Logout': 'Выйти',
	'Update': 'Обновить',
	'EnterName': 'Введите имя',
	'EnterEmail': 'Введите почту',
	'EnterPassword': 'Введите пароль',
	'ConfirmPassword': 'Подтвердите пароль',
	'EnterOldPassword': 'Введите старый пароль',
	'EnterNewPassword': 'Введите новый пароль',
	'ChangePassword': 'Изменить пароль',
	'ChoseLanguage': 'Выберите язык',
	'StayMessage': 'Оставьте сообщение',
	'SendReview': 'Отправить отзыв',
	'Years': 'Лет',
	'Pages': 'Страниц',
	'Description': 'Описание',
	'Register': 'Регистрация',
	'Login': 'Войти',
	'YouDontHaveAfavoriteBook': 'У вас нет избранных книг',
	'YouDontHaveAStartedBook': 'У вас нет начатых книг',
	'YouDontHaveAFinishedBook': 'У вас нет прочитанных книг',
	'CharacterProgress': 'Прогресс главы:',
	'of': 'из',
	'pages': 'страниц',
	'Characters': 'Главы',
	'You text must be a minimum 20 letter!': 'Ваш текст должен быть минимум 20 символов!',
'Send Review': 'Отправить отзыв',
	"Terrable": "Ужасно",
	"Bad": "Плохо",
	"Normal": "Нормально",
	"Good": "Хорошо",
	"Excellent": "Отлично",
	'Go Read': 'Читать',
	'Delete book': 'Удалить книгу',
'add': 'Добавить',
	'None review!': 'Нет отзывов!',
	'Send': 'Отправить',
	'Are you sure you want to logout from your account?'	: 'Вы уверены, что хотите выйти из аккаунта?',
	'LOGOUT': 'ВЫЙТИ',
}
